- name: Linting
  uses: snakemake/snakemake-github-action@v1.18.0
  with:
    directory: '.test'
    snakefile: 'workflow/Snakefile'
    args: '--lint'
- name: Testing
  uses: snakemake/snakemake-github-action@v1.18.0
  with:
    directory: '.test'
    snakefile: 'workflow/Snakefile'
    args: '--cores 1 --configfile .tests/integration/test_config.yaml --use-conda --conda-cleanup-pkgs cache'
