sample_table: "resources/test/sample_table.tsv"
shiver_config_file: "config/shiver_config.sh"
human_reference_genome: "resources/GRCh38_latest_genomic.fna"
viral_species: "SARS-CoV-2"
viral_reference_genome: "resources/{viral_species}/MyRefAlignment.fasta"
viral_reference_gene_features: "resources/{viral_species}/MyRefFeatures.gff3"
viral_sequencing_adapters: "resources/{viral_species}/MyAdapters.fasta"
viral_sequencing_primers: "resources/{viral_species}/MyRefAlignment.fasta"
