sample_table: ".tests/integration/sample_table.tsv"
shiver_config_file: "config/shiver_config.sh"
human_reference_genome: ".tests/integration/dummy_human_genome.fna"
viral_species: "LASV_S"
viral_reference_alignment: "resources/{viral_species}/MyRefAlignment.fasta"
viral_reference_genome: "resources/{viral_species}/MyRefGenome.fasta"
viral_reference_gene_features: "resources/{viral_species}/MyRefFeatures.gff3"
viral_sequencing_adapters: "resources/{viral_species}/MyAdapters.fasta"
viral_sequencing_primers: "resources/{viral_species}/MyRefAlignment.fasta"
